//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthcareData.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthcareSoftwareEntities : DbContext
    {
        public HealthcareSoftwareEntities()
            : base("name=HealthcareSoftwareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblClinicAdministrator> tblClinicAdministrators { get; set; }
        public virtual DbSet<tblClinicDoctor> tblClinicDoctors { get; set; }
        public virtual DbSet<tblClinicMaintenance> tblClinicMaintenances { get; set; }
        public virtual DbSet<tblClinicManager> tblClinicManagers { get; set; }
        public virtual DbSet<tblClinicPatient> tblClinicPatients { get; set; }
        public virtual DbSet<tblHealthcareInstitution> tblHealthcareInstitutions { get; set; }
        public virtual DbSet<tblHealthcareUserData> tblHealthcareUserDatas { get; set; }
        public virtual DbSet<tblSickLeaveRequirement> tblSickLeaveRequirements { get; set; }
    }
}
