//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthcareData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClinicManager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblClinicManager()
        {
            this.tblClinicDoctors = new HashSet<tblClinicDoctor>();
        }
    
        public int ClinicManagerID { get; set; }
        public int UserDataID { get; set; }
        public int FloorNumber { get; set; }
        public int MaxCountOfDoctors { get; set; }
        public int MinCountOfRooms { get; set; }
        public int OmissionsCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClinicDoctor> tblClinicDoctors { get; set; }
        public virtual tblHealthcareUserData tblHealthcareUserData { get; set; }
    }
}
