//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthcareData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClinicDoctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblClinicDoctor()
        {
            this.tblClinicPatients = new HashSet<tblClinicPatient>();
        }
    
        public int ClinicDoctorID { get; set; }
        public int UserDataID { get; set; }
        public string Number { get; set; }
        public string BankAccountNo { get; set; }
        public string Department { get; set; }
        public string Shift { get; set; }
        public bool IsInChargeOfAdmissionOfPatients { get; set; }
        public Nullable<int> ClinicManagerID { get; set; }
    
        public virtual tblClinicManager tblClinicManager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClinicPatient> tblClinicPatients { get; set; }
        public virtual tblHealthcareUserData tblHealthcareUserData { get; set; }
    }
}
