//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthcareData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHealthcareInstitution
    {
        public int HealthcareInstitutionID { get; set; }
        public System.DateTime CompletionDate { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Address { get; set; }
        public int NumberOfFloors { get; set; }
        public int NumberOfPersonsPerFloor { get; set; }
        public bool HasBalcony { get; set; }
        public bool HasBackyard { get; set; }
        public Nullable<int> NumberOfAmbulanceAccess { get; set; }
        public Nullable<int> NumberOfDisabledPersonsAccess { get; set; }
    }
}
