//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthcareData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSickLeaveRequirement
    {
        public int SickLeaveRequirementID { get; set; }
        public int ClinicPatientID { get; set; }
        public System.DateTime RequirementDate { get; set; }
        public string RequirementCause { get; set; }
        public string CompanyName { get; set; }
        public bool IsEmergency { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual tblClinicPatient tblClinicPatient { get; set; }
    }
}
